styleguide: plataformatec/linters
engines:
  credo:
    enabled: true
  fixme:
    enabled: true
  remark-lint:
    enabled: true

exclude_paths:
- config
- priv/repo
- test

pull_requests:
  enabled: true
  comments: true
