language: elixir
elixir:
  - 1.4.0
addons:
  apt:
    packages:
      - postgres

install:
  - mix local.hex --force
  - mix local.rebar --force
  - mix do deps.get, deps.compile

before_script:
  - mix do ecto.create, ecto.migrate
  - echo 'Users.count("http://jsonplaceholder.typicode.com/users")' | iex -S mix

script:
  - MIX_ENV=test mix coveralls.travis test/*

notifications:
  email: false
