language: elixir
elixir:
  - 1.4.0

install:
  - mix local.hex --force
  - mix local.rebar --force
  - mix deps.get
  - mix deps.compile

env:
  - MIX_ENV=test

script:
  - mix test test/*
  - mix coveralls.travis

notifications:
  email: false
