language: elixir
elixir:
  - 1.4.0

install:
  - mix local.hex --force
  - mix local.rebar --force
  - mix deps.get
  - mix deps.compile

script:
  - MIX_ENV=test mix test test/*

after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
  email: false
