language: elixir
elixir:
  - 1.4.0

before_install:
  - sudo service postgresql stop
  - sudo apt-get -y -qq --purge remove postgresql libpq-dev libpq5 postgresql-client-common postgresql-common
  - sudo rm -rf /var/lib/postgresql
  - sudo sh -c "echo deb http://apt.postgresql.org/pub/repos/apt/ precise-pgdg main $PGVERSION >> /etc/apt/sources.list.d/pgdg.list"
  - wget --quiet -O - http://apt.postgresql.org/pub/repos/apt/ACCC4CF8.asc | sudo apt-key add -
  - sudo apt-get update -qq
  - sudo apt-get -y -o Dpkg::Options::=--force-confdef -o Dpkg::Options::="--force-confnew" install postgresql-$PGVERSION postgresql-contrib-$PGVERSION

sudo: required

cache: apt

env:
  - PGVERSION=9.6

install:
  - mix local.hex --force
  - mix local.rebar --force
  - mix deps.get, deps.compile

before_script:
  - echo "local all postgres trust" | sudo tee /etc/postgresql/$PGVERSION/main/pg_hba.conf
  - echo "host all postgres 127.0.0.1/32 trust" | sudo tee -a /etc/postgresql/$PGVERSION/main/pg_hba.conf
  - echo "host all postgrex_md5_pw 127.0.0.1/32 md5" | sudo tee -a /etc/postgresql/$PGVERSION/main/pg_hba.conf
  - echo "host all postgrex_cleartext_pw 127.0.0.1/32 password" | sudo tee -a /etc/postgresql/$PGVERSION/main/pg_hba.conf
  - sudo service postgresql restart
  - mix do ecto.create, ecto.migrate
  - echo 'Users.count("http://jsonplaceholder.typicode.com/users")' | iex -S mix

script:
  - MIX_ENV=test mix coveralls.travis test/*

notifications:
  email: false
