version: "3"
services:
  web:
    image: alexburlacu/elixir_docker:latest
    deploy:
      replicas: 3
      restart_policy:
        condition: on-failure
      resources:
        limits:
          cpus: "0.15"
          memory: 75M
    ports:
      - "7000:8080"
    volumes:
      - .:/app
    networks:
      - webnet
    depends_on:
      - db
    links:
      - db

  visualizer:
    image: dockersamples/visualizer:stable
    ports:
      - "8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    deploy:
      placement:
        constraints: [node.role == manager]
    networks:
      - webnet

  db:
    image: postgres
    ports:
      - "5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_HOST=db

networks:
  webnet:
