version: "3"
services:
  web:
    image: alexburlacu/elixir_docker:latest
    # build: Dockerfile
    deploy:
      replicas: 3
      restart_policy:
        condition: on-failure
      resources:
        limits:
          cpus: "0.15"
          memory: 75M
    ports:
      - "7000:8080"
    volumes:
      - .:/app
    depends_on:
      - db
    # command: sh init_db.sh
    # links:
    #   - db

  db:
    image: postgres
    volumes:
      - "/run/postgresql:/run/postgresql"
    ports:
      - "5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_HOST=db
